name = "jiwonz/pathfs"
version = "0.5.1"
description = "luau-path + @lune/fs"
authors = ["jeparlefrancais <jeparlefrancais21@gmail.com>", "jiwonz <me@jiwonz.kr>"]
repository = "https://github.com/jiwonz/lune-path-fs/"
license = "MIT"
includes = ["README.md", "pesde.toml", "src/**", "LICENSE"]

[target]
environment = "lune"
lib = "src/lib/init.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]
luau_path = { name = "jiwonz/luau_path", version = "^0.1.1", target = "luau" }
greentea = { name = "corecii/greentea", version = "^0.4.11" }

[dev_dependencies]
frktest = { name = "itsfrank/frktest", version = "^0.0.2" }
luau_lsp = { name = "pesde/luau_lsp", version = "^1.38.1" }
selene = { name = "pesde/selene", version = "^0.28.0" }
stylua = { name = "pesde/stylua", version = "^2.0.2" }
